### ISSUE TITLE
Build failed using System JS

### ISSUE THREAD

**Issue by johnidm** [voliva/angular2-interceptors#12]
Hi 

When I run the command `npm run build` this error occurred `Uncaught TypeError: Cannot read property 'InterceptedRequest' of undefined`.

But, when I use `npm serve` this error doesn't occur.

I created a repositry on GitHub to reproduce the error https://github.com/johnidm/ng2-interceptor-problem

I am using System JS to load `ǹg2-interceptor`: https://github.com/johnidm/ng2-interceptor-problem/blob/master/src/systemjs.conf.js

I am following this set up InterceptorService https://github.com/johnidm/ng2-interceptor-problem/blob/master/src/app/app.module.ts#L29

**Comment by voliva** [comment]
Can you try with v1.2.1 I published now? Haven't tried, but it seems like SystemJS doesn't like interfaces in javascript (mainly because they don't exist), I have removed the references in index.js file.

**Comment by johnidm** [comment]
@voliva thanks for attention, this works fine with v1.2.1

**Comment by voliva** [comment]
Thank you too :) I will push the changes done this evening to github.
