### ISSUE TITLE
It can not install for angular 2.4.1

### ISSUE THREAD

**Issue by zhanxp** [voliva/angular2-interceptors#16]
angular 2.4.1 is requires  rxjs@^5.0.1 
angular2-interceptors is requires rxjs@5.0.0-beta.12
so I can not install it to my project.

**Comment by prog110** [comment]
@voliva Is there any plan to change this soon?

**Comment by voliva** [comment]
@thekalinga I have a commit on the branch [versionupdate](https://github.com/voliva/angular2-interceptors/tree/versionUpdate?files=1) that should fix this. I'm trying to include more changes to fix other issues.

However, as I understand this is critical I hope to release it today, and continue working on other issues in another branch.

**Comment by voliva** [comment]
Can you try again with v1.3.0-0?
