### ISSUE TITLE
Version constraint on peer dependency on rxjs is too tight

### ISSUE THREAD

**Issue by leonboot** [voliva/angular2-interceptors#23]
The version constraint on the peer dependency for the rxjs library is specified to be **exactly** 5.0.0-beta.12 in the `master` branch and 5.0.0 in the `feature/versionUpdate` branch. This makes this library impossible to use in projects that depend on any other version of the rxjs library. Unless I'm mistaken, I don't think this library depends on rxjs functionality only present in version 5.0.0, so loosening up the version constraints by placing a caret in front of it should make it a whole lot more usable.

**Comment by voliva** [comment]
Thanks! Fixed through #24

**Comment by voliva** [comment]
Released on version 1.3.0-1
